################################################################################
# Secret:      mysql-creds
# Description: Environment variables:
# Variables:   * MYSQL_ROOT_PASSWORD: Instances password for the root user
#              * MYSQL_USER: Instance user name for user database
#              * MYSQL_PASSWORD: Instance user password
#              * MYSQL_DATABASE: Name of the user database
#              * MYSQL_SOURCE_USER: This user is for replication purposes, 
#                avoiding using root credentials
#              * MYSQL_SOURCE_PASSWORD: Replication user password
#              * MYSQL_BACKUP_USER: This user is for clone purposes, avoiding
#                using root credentials
#              * MYSQL_BACKUP_PASSWORD: Backup user password
#              * RRC_HLSERVICE: Name of the headless service
# Files:       None
################################################################################
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
  name: mysql-creds
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootPassword
  MYSQL_USER: testuser
  MYSQL_PASSWORD: testPassword
  MYSQL_DATABASE: test
  MYSQL_BACKUP_USER: backupuser
  MYSQL_BACKUP_PASSWORD: backupPassword
  MYSQL_SOURCE_USER: replicator
  MYSQL_SOURCE_PASSWORD: replicatorPassword
  RRC_HLSERVICE: interconnect