################################################################################
# StatefulSet: mysql    
# Description: MySQL Read Replica Cluster (RRC) main resource. It creates 
#              MySql instance pods in an orderly manner using ORDINALS, a number
#              greater than or equal to zero:
#              The first created pod, mysql-0, is the source instance
#              The second, third, ... are read replicas
#              Pod creation process has three phases
#              * Phase 1 (image name: rrc-pre). This phase clone the database 
#                from its "left buddy", using Percona Xtrabackup utilities. 
#                (xbstream for restore and xtrabackup --prepare for preparation)
#                This phase must be executed prior to the database init process, 
#                so it's defined in the initContainers section of the 
#                StatefulSet. Also, this phase is ignored for the Source 
#                instance as there's no "left buddy" to clone from
#              * Phase 2 (image name: rrc-mysql). This phase starts the MySQL 
#                instance as Source role (StatefulSet ordinal = 0) or Replica 
#                role (ordinal > 0). For the Source instance the database is 
#                initialized, including the creation of the following extra 
#                database objects:
#                o The Replication user, to avoid using the root credentials 
#                  for replication activities. The following environment 
#                  variables are needed: MYSQL_SOURCE_USER and 
#                  MYSQL_SOURCE_PASSWORD
#                o The Clone user, to avoid using the root credentials for 
#                  the backup process. The following environment variables
#                  are needed: MYSQL_BACKUP_USER and MYSQL_BACKUP_PASSWORD
#              * Phase 3 (image name: rrc-post). This phase waits for the
#                previous one (MySQL start) and request to the source instance
#                to start a replication process from the clone position, 
#                avoiding thus to start replication from "the begining of time". 
#                Of course, this request is only needed in replicas. 
#                In either case (source or replicas) it start a "backup server"
#                to be consumed by its "right buddy" as the clone source
#                           
################################################################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
  name: mysql
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/name: mysql
  serviceName: interconnect
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: mysql
    spec:
      initContainers:
      # Clone from the "left buddy"
      - name: rrc-pre
        image: quay.io/jnmalledo/sts-rrc-utils:1.1
        imagePullPolicy: Always 
        command:
        - /opt/rrc/rrc-pre
        env:
        # The name of the headless service
        - name: RRC_HLSERVICE
          valueFrom:
            secretKeyRef:
              key: RRC_HLSERVICE
              name: mysql-creds
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-vol
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      containers:
      # MySQL start
      - name: rrc-mysql
        image: registry.redhat.io/rhel9/mysql-80:latest
        imagePullPolicy: Always
        command:
        - /opt/rrc/rrc-run-mysqld
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mysql-creds
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-creds
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-creds
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: mysql-creds
        - name: MYSQL_SOURCE_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_SOURCE_USER
              name: mysql-creds
        - name: MYSQL_SOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_SOURCE_PASSWORD
              name: mysql-creds
        - name: MYSQL_BACKUP_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_BACKUP_USER
              name: mysql-creds
        - name: MYSQL_BACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_BACKUP_PASSWORD
              name: mysql-creds
        ports:
        - containerPort: 3306
          name: mysql-port
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /opt/rrc/rrc-instance-alive
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /opt/rrc/rrc-instance-ready
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-vol
        - mountPath: /opt/rrc
          name: rrc-vol
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: rrc-post
        image: quay.io/jnmalledo/sts-rrc-utils:1.1
        imagePullPolicy: Always
        command:
        - /opt/rrc/rrc-post
        env:
        # The name of the headless service
        - name: RRC_HLSERVICE
          valueFrom:
            secretKeyRef:
              key: RRC_HLSERVICE
              name: mysql-creds
        - name: MYSQL_SOURCE_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_SOURCE_USER
              name: mysql-creds
        - name: MYSQL_SOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_SOURCE_PASSWORD
              name: mysql-creds
        - name: MYSQL_BACKUP_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_BACKUP_USER
              name: mysql-creds
        - name: MYSQL_BACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_BACKUP_PASSWORD
              name: mysql-creds
        # IMPORTANT: DO NOT CONFIGURE TCP PROBES on clone-port (3307)!!!
        # Every TCP connection triggers a full backup!!!
        ports:
        - containerPort: 3307
          name: clone-port
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-vol
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
    
      # This is needed for private registry pulling
      imagePullSecrets:
      - name: rh-registry-creds
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30

      # Script configmap
      volumes:
      - configMap:
          defaultMode: 509
          name: rrc-scripts
        name: rrc-vol
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending

